name: flutter_counter
description: Counter sample using bloc package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.3.0"

dependencies:
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
